import re
from loguru import logger

class Storyboarder:
    """
    Parses a structured script from the brain into a list of scenes.
    """
    def __init__(self):
        logger.info("🎬 Storyboarder initialized.")

    def parse_script(self, script_text: str) -> list:
        """
        Parses the script text into a list of scene dictionaries.

        Args:
            script_text: The structured script generated by the brain.

        Returns:
            A list of scenes, where each scene is a dictionary containing
            the description and dialogue. Returns an empty list if parsing fails.
        """
        scenes = []
        try:
            scene_blocks = re.findall(r'\[SCENE_START\](.*?)\[SCENE_END\]', script_text, re.DOTALL)

            for block in scene_blocks:
                scene_data = {}

                desc_match = re.search(r'SCENE_DESCRIPTION:\s*(.*)', block, re.IGNORECASE)
                if desc_match:
                    scene_data['description'] = desc_match.group(1).strip()

                dialogue = {}
                dialogue_matches = re.findall(r'(\w+):\s*(.*)', block)
                for char, line in dialogue_matches:
                    if char.upper() in ["SARJANA", "DURJANA"]:
                        dialogue[char.upper()] = line.strip()

                scene_data['dialogue'] = dialogue
                scenes.append(scene_data)

            logger.info(f"✅ Successfully parsed {len(scenes)} scenes.")
            return scenes

        except Exception as e:
            logger.error(f"🚨 Error parsing script: {e}", exc_info=True)
            return []
